Cargo.lock, config.json, sim-cli/Cargo.toml, sim-cli/src/main.rs, sim-lib/Cargo.toml, sim-lib/src/lib.rs
parses config using serde and prints it
=> feat: sketch sim-cli

sim-lib/src/lib.rs
Adds the activity definition structure we'll be using to parse the input file
=> Adds generic activity definition struct

Cargo.lock, config.json, sim-cli/Cargo.toml, sim-cli/src/main.rs, sim-lib/Cargo.toml, sim-lib/src/lib.rs, sim-lib/src/lnd.rs
connect to Lnd node, and init simulator
=> feat: node connect

sim-lib/src/lib.rs
`config.json` naming will need to be updated accordingly
=> Normalizes the ActivityDefinition field names

Cargo.lock, sim-cli/src/main.rs, sim-lib/Cargo.toml, sim-lib/src/lib.rs, sim-lib/src/lnd.rs
implement get node info for lnd
=> feat: get node info

sim-cli/src/main.rs, sim-lib/src/lib.rs
=> Provide Summary Logging for Payment Dispatch + Cleanup Payment Hashes

sim-lib/src/lib.rs
`tokio::select` for `produce_events` was not working correctly. The way it was structured, `send` will always be ready. Therefore payments were not respecting the intervals set by `time::timeout`.
This was introduced by #46 
#Opsie :/
=> hotfix: Fixes select for produce_events

README.md
Updated to include the new json format.
=> readme: update config and implementation support with CLN

README.md
Add log level flag to run example. Cli doesn't run for me without it.
=> Update README add log level to run command

Cargo.lock, sim-lib/Cargo.toml, sim-lib/src/lib.rs, sim-lib/src/serializers.rs
=> sim-lib: allows user folder shortcuts (~) in config

Cargo.lock, README.md, sim-cli/src/main.rs, sim-lib/src/lib.rs, sim-lib/src/serializers.rs
A few logging improvements I noticed while using simln (for my real world real job!!!!!) today 🧹
=> nit: Logging Fixups

docs/ARCHITECTURE.md, sim-lib/src/lib.rs
Before we run through another round of changes, let's standardize naming a little.
=> refactor: Standardize names and add Arch Doc

sim-lib/src/cln.rs, sim-lib/src/lib.rs, sim-lib/src/lnd.rs
closes https://github.com/bitcoin-dev-project/sim-ln/issues/29
=> chore: validate node network and disallow mainnet

sim-lib/src/cln.rs
Looks like the issue was with the testing instance and not with the current version of `cln-grpc`
Close #85
=> Removes TODO regarding CLN features

.github/workflows/main.yml, sim-lib/src/lib.rs
Updates clippy to use maintained actions, plus fixes clippy issues.
=> sim-lib: Fixes clippy issues

sim-cli/src/main.rs
The current `capacity_multiplier` deserializer accepts values smaller than or equal to 0, which are not allowed by the simulator. Patch it with a custom f64 deserializer that enforcer values to be greater than zero
This is related to #155.
=> sim-cli: improves capacity_multiplier deserializer

Cargo.lock
=> cargo: update time dependency

sim-cli/src/main.rs
=> sim-cli: use updated log level for sim-lib

README.md
=> readme: add protoc to requirements

simln-lib/src/sim_node.rs
=> simln-lib: remove unnecessary async in SimNode trait
