Cargo.lock
sim-lib/Cargo.toml
sim-lib/src/lib.rs

Breaking things up into steps to allow us to work independently, the output at each phase feeds into the next one: 
* Phase 0: user input in config file (as specified in #2)
* Phase 1: parsed activity description + LN clients for each node 
* Phase 2:  generated queue of events (this PR)
* Phase 3: CSV file of results

sim-lib: Add event queue common structs

---

Cargo.lock
sim-cli/src/main.rs
sim-lib/Cargo.toml
sim-lib/src/lib.rs
temp

This PR adds event generation and execution for our simulation. This is done using async channels and a consumer/producer pattern: 
* For each `node` that we have execution on, we start a `consumer` thread that will receive events and execute them on the underlying lightning node. 
* For each `activity_description` that we have, we push out an event to the appropriate consumer at the interval that's requested.

Add Event Consumer and Producer

---

Cargo.lock
sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-lib/src/lib.rs

Lets now use prints nor anyhows to bubble up errors :)
Close #24

Gets rid of prints and anyhows on the lib

---

sim-cli/src/main.rs
sim-lib/src/lib.rs
sim-lib/src/lnd.rs

This modifies the LightningNode trait with respect to get_info. Now instead of implementing the get_info rpc command on LightningNode::get_info we set that as a getter to NodeInfo, and NodeInfo is built calling the rpc command on LndNode::new.

Reworks LndNode so we persist NodeInfo within it

---

sim-lib/src/lib.rs
sim-lib/src/lnd.rs

Methods of LndNode that call gRPC methods need to access the client mutably. Our traits for LightningNode were defined not to be mutable, meaning we would need to clone the client mutable for every single method.
Let's keep things simple

Makes methods that interact with lnd mutable

---

sim-lib/src/lib.rs

Adds a comment for #54. 
Single producer channels don't exist in tokio, but we put a note here to keep ourselves safe in future.

sim-lib: note that multi-producer requires shutdown trigger

---

Cargo.lock
sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-lib/src/lib.rs

capture sigterm from `sim-cli` and issue simulation shutdown. this allows us to complete tasks like report writing, before simulation exit
fixes #58

feat: clean shutdown simulation on sigterm

---

sim-lib/src/lib.rs

We really don't need a trigger in consume_events. If a consumer is dropped, the channel is dropped, and the consumer will be signaled through the channel and break the execution already

Removes triggers from consume_events

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

Simplifies the JoinSet management to have a single global set of tasks
Also adds a cli param to control the total simulation runtime (`--total-time`)
Close #38

Adds a global timeout

---

sim-lib/src/lib.rs
sim-lib/src/lnd.rs
sim-lib/src/serializers.rs

uses serializable `FailureReason` that we can then show in the generated report
```
source,destination,hash,amount_msat,dispatch_time,settled,htlc_count,failure_reason
02dd7ca90bac8579b7c5aa8b6eece032327b12f14314c59323d9ff9a5b65e1a63c,0378f52c4a103734795040a7d563df24a59c091a1d25d7acb3041a99bde8afbd13,43ebabbb538d9619042a066ad647d6ff80beeb6f5010113d4e87ff75f505f186,10000,1692366457128,true,0,RouteNotFound
02dd7ca90bac8579b7c5aa8b6eece032327b12f14314c59323d9ff9a5b65e1a63c,0378f52c4a103734795040a7d563df24a59c091a1d25d7acb3041a99bde8afbd13,bce62bc0b782904190d9a9dded1aabbb4c652f361531d28b184921b3dac23122,10000,1692366459132,true,0,RouteNotFound
```
fixes #63

fix: show failure reason in csv report

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

Debug logs can be turned in using `--debug`.
Also fixes pending logs.

Adds debug arg to the CLI

---

sim-cli/src/main.rs

This replaces the old `--debug` flag which was less flexible.
Improves on #71 
Close #61

Adds support to multiple log levels via `--log_level`

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

batch print results to csv

---

sim-lib/src/cln.rs
sim-lib/src/lib.rs
sim-lib/src/lnd.rs

Currently we were using a pretty hacky way of parsing LND features that only parsed the keysend feature (given is the only we care about atm).
This PR properly loads the feature vector returned by LND's GetNodeInfo and parses it so a complete NodeFeatures object can be constructed.
Also sets NodeInfo::features to NodeFeatures for consistency

Normalizes node features so they use LDK NodeFeatures

---

sim-lib/src/cln.rs

Polls `lightning-listpays` until payment completes or fails

feat: track payment on cln nodes

---

Cargo.lock
Cargo.toml
sim-cli/Cargo.toml
sim-lib/Cargo.toml
sim-lib/src/cln.rs

Fixes #87.
We've ignored a warning: 
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"
```
Which means that `cargo install` breaks: 
```
error[E0308]: mismatched types
--> sim-lib/src/cln.rs:78:17
|
78 |                 alias,
|                 ^^^^^ expected `String`, found `Option<String>`
|
= note: expected struct `std::string::String`
found enum `std::option::Option<std::string::String>`
For more information about this error, try `rustc --explain E0308`.
```
I _think_ that this happened when we bumped minimum rust version via some dependency.

multi: update workspace resolver and fix cln alias

---

sim-lib/src/lib.rs
sim-lib/src/lnd.rs

There were two dead-code tags that may have been missed from the last cleanup

sim-lib: cleans unnecessary dead-code tags

---

sim-cli/Cargo.toml
sim-lib/Cargo.toml

Resolver is only required at a workspace level to clear the warning we were getting.

multi: remove redundant resolver

---

README.md

Without `--locked`, `cargo install` is free to upgrade dependencies to any minor versions. 
This can cause problems: see [issue](https://github.com/bitcoin-dev-project/sim-ln/issues/87), [original report](https://github.com/bitcoin-dev-project/sim-ln/pull/88#pullrequestreview-1625226199) and [summary](https://github.com/bitcoin-dev-project/sim-ln/pull/88#issuecomment-1719880940) for details.

readme: lock cargo install

---

sim-lib/src/lnd.rs

When we don't set a fee limit for payments, LND will set the limit to the amount of the payment. This can make smaller payments fail in scenarios where the default base fee is more than the payment amount.
We update our sending code to have no fee limit, because we're more concerned with payment activity than fees. If we'd like to think about fees, we'll surface this on an activity and pass it through.

lnd: set no fee limit on payments

---

sim-lib/src/lib.rs

Directly reporting an error above from call to `get_node_features` of the destination node is confusing, and makes it seem like we don't check destination node in activity validation.
fixes #92 , #95

sim-lib/validation: consistently report validation errors

---

sim-lib/src/cln.rs
sim-lib/src/lib.rs
sim-lib/src/lnd.rs
sim-lib/src/serializers.rs

Instead of stopping the simulation on the first send payment rpc error, we gracefully handle the error and report a default send payment result. Since send payment rpc might fail before dispatching a payment (i.e in CLN case), we allow activity result reporting to skip tracking of payment if there's no payment hash
Sample results with failed keysends. The simulation continues until stopped
```csv
source,destination,hash,amount_msat,dispatch_time,htlc_count,payment_outcome
023d45dc57ed99e6d793e2fed8dcf79d2f6ad2f32ec31b48102de445e245e08336,03b73874dde2c0af24619f03b6fc5d36adbf00ad6d25ce6479d4f5b60f648c8cb6,83d340ab8a7f7b383294dd06a8fc02bcbff6c77c73debaa8e590aad550216f98,1000,1695160575397,1,Success
02c0c854f511082f9d174f9b0e51ca14fc299c25de9d65dddadebe9ac1fd529758,03b73874dde2c0af24619f03b6fc …
```

sim-lib: continue simulation on send payment errors

---

sim-lib/src/cln.rs
sim-lib/src/lib.rs
sim-lib/src/lnd.rs

The current approach to get the network from a node stores the information in `NodeInfo`. 
However, this is troublesome going forward (after #103) given we will start using `NodeInfo` to store information about nodes we do not control (and from which we cannot query the network). Furthermore, the network information is worthless once we've sanity-checked that we are running on a network we support and all nodes are running on the same one, so there is no point keeping that around

sim-lib: Adds LightningNode::get_network

---

sim-cli/src/main.rs
sim-lib/src/cln.rs
sim-lib/src/lib.rs
sim-lib/src/lnd.rs
sim-lib/src/random_activity.rs
sim-lib/src/serializers.rs

The goal of this PR is to allow aliases to be used throughout the config file to identify nodes, so the file is more human-readable. This involves:
\* We cannot use aliases as `destination` for nodes we don't control, given we have no way of mapping the aliases to the nodes' public keys. Notice aliases here do not have to match node aliases, they are just user-defined identifiers, and even if they did, node aliases don't have to be unique.

Allows using aliases within the config file

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

Currently we are using the term config file for the file that contains the simulation details. This is kind of fine for now, but it will get messy down the line when we want to start storing default values for the CLI parameters in a config file. Furthermore, we are requiring the config file to be passed, but `--config` is required.
This both renames config to sim, and makes the parameter positional instead of named.

Renames config file to sim file

---

sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-lib/Cargo.toml

Mainly so we can have something nice when running `--help`

sim-all: Adds description to both existing creates

---

.dockerignore
.gitignore
Makefile
README.md
docker/Dockerfile
docker/README.md
docker/build.sh
docker/entrypoint.sh
docker/setup-volume.sh

To run:
```
CONFIG_PATH=/path-to-project/sim-ln/config.json docker-compose run sim-cli
```

chore: add docker

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

`sim-cli help` is pretty unfriendly atm, add docs so the args/options are covered. 
This makes some optional params to the simulator mandatory and moves the defaulting behavior to the CLI so clap can take care of it. The main rationale for it is so we can easily report the defaults.
Also, restricts `print_batch_size` to be `> 0`, as discussed https://github.com/bitcoin-dev-project/sim-ln/pull/146#issuecomment-1771101726

sim-cli: Improves CLI docs so help has a more friendly report

---

sim-cli/src/main.rs
sim-lib/src/lib.rs

It is rather annoying to run the simulator and have to delete the output files when we are doing testing/dev. This allows us to do so without the file being created.

sim-all: Allow running the simulator without it writing on disk

---

Cargo.lock
sim-cli/Cargo.toml

@dependabot is complaining about issues with a couple of our dependencies.
This PR fixes the ones related to `simple_logger` (https://github.com/bitcoin-dev-project/sim-ln/security/dependabot/1)
The ones related to `webpki` (https://github.com/bitcoin-dev-project/sim-ln/security/dependabot/3) will be fixed with #148, given they come from old versions of `rustls` and `tonic` wich are imported by `tonic_lnd`.

Bumps simple_logger version to get rid of atty dependency

---

Cargo.lock
README.md
sim-lib/Cargo.toml
sim-lib/src/lnd.rs

- The new version of fedimint-tonic-lnd supports connecting to LND nodes using IP addresses

chore: bump fedimint-tonic-lnd version

---

README.md
docker/README.md
sim-cli/src/main.rs
sim-lib/src/lib.rs

I must have been way more sleep-deprived than I thought when originally designing this, but we don't really need the nested json with node type tags to parse node information (as long as the node info has, **at least** one different field name).
Mainly, this goes from:
```json
"nodes": [
{
"LND": {
"id": "...",
"address": "...",
"macaroon": "...",
"cert": "..."
}
},
{
"CLN": {
"id": "...",
"address": "...",
"ca_cert": "...",
"client_cert": "...",
"client_key": "..."
}
}
]
```
To:
```json
"nodes": [
{
"id": "...",
"address": "...",
"macaroon": "...",
"cert": "..."
},
{
"id": "...",
"address": "...",
"ca_cert": "...",
"client_cert": "...",
"client_key": "..."
}
]
```

sim-lib: Get rid of nested json for node definition

---

Cargo.lock
sim-cli/src/main.rs
sim-lib/Cargo.toml
sim-lib/src/lib.rs
sim-lib/src/random_activity.rs
sim-lib/src/test_utils.rs

This is a first stab at adding tests to the simulator.
Adds tests to the random activity generator and includes some sanity checks to `sim-cli` so we can fail early if we need to.

sim-all: Adds tests coverage to `random_activity`

---

sim-cli/src/main.rs

u64 parser does not work for a f64 value. 
Broken on main:
```
sim-cli sim.json
thread 'main' panicked at 'Mismatch between definition and access of `capacity_multiplier`. Could not downcast to TypeId { t: 8711759054683223602271599665973969982 }, need to downcast to TypeId { t: 25882202575019293479932656973818029271 }
', /Users/carla/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.6/src/parser/error.rs:32:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
sim-cli sim.json --capacity-multiplier 0.5
error: invalid value '0.5' for '--capacity-multiplier <CAPACITY_MULTIPLIER>': invalid digit found in string
```

sim-cli: remove broken parser for activity multiplier

---

.gitignore
Cargo.lock
README.md
sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-lib/src/lib.rs

Introduces `SIM_LN_DATA_DIR` from which `sim-cli` sources simulation files and writes simulation outputs.

sim-cli: source simulation file from data directory

---

Makefile
docker/Dockerfile
docker/README.md
docker/entrypoint.sh
docker/setup-volume.sh

- modifies the volume setup script for sim.json config
- adds --data-dir to CMD args (default is /data in volume)
- fix entrypoint.sh script

fix: issue with docker config and volume setup

---

.gitignore
sim-cli/src/main.rs
sim-lib/src/defined_activity.rs
sim-lib/src/lib.rs
sim-lib/src/random_activity.rs
sim-lib/src/test_utils.rs

This PR unifies dispatch of random and defined activities. I think that this is worthwhile doing: 
1. As a pathway to allowing users to specify *both* random and defined activity in future changes
2. To reduce code duplication (functionality is similar in `produce_events` and `produce_random_events`)
3. Possibly provide a different impl of things like #153 (though the existing one is quite simple so this is a weak motivation)
Opening up in draft for an early look (**still needs some cleanup**). This is my first foray into trait objects, so this PR only exists by the good graces of [crust of rust](https://www.youtube.com/watch?v=xcygqF5LVmM&list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa) / suggestions for more canonical rust ways of doing this are very welcome!

refactor: Unify Dispatch of Random and Defined Activity

---

docker/README.md
docker/setup-volume.sh

Inspired by testing #159 and re-feelin the magic of `sim.json` files being magically converted to work with docker ✨ 
This PR just replaces `localhost` -> `host.docker.internal` since it's pretty likely that everything is being used on the same machine if you're using localhost. With this change, you don't need to change your local `sim.json` to use docker _at all_!

docker: add localhost replacement to volume setup

---

Cargo.lock
sim-lib/Cargo.toml
sim-lib/src/lib.rs
sim-lib/src/sim_node.rs

This PR is a WIP that adds the ability to run SimLN without any real lightning nodes, instead providing "simulated nodes" that copy the the routing policies and liquidity constraints of real nodes. The last commit hard-codes a graph to run this "full simulation" on as an example, whereas in reality we'd load from a json description of the desired topology/policies.
Lightning implementations in SimLN are abstracted using the [LightningNode](https://github.com/bitcoin-dev-project/sim-ln/blob/main/sim-lib/src/lib.rs#L180) trait. The steps that we follow to support a simulated implementation of this trait (SimNode) are as follows: 
- Run the simulator with a `–from_graph option`, which allows starting the simulator with a graph file (format tbd) that provides channel policies and topology …

Add Ability to Run as Full Simulator

---

Cargo.lock
sim-lib/Cargo.toml
sim-lib/src/sim_node.rs

This PR adds coverage for our simulated network and (unsurprisingly) squashes some bugs: 
* Do not double-return liquidity for failed HTLCs: previously we'd return liquidity to local balance on failures twice over
* Off by one removal: if a HTLC failed at index 0, we would not remove the first HTLC because our loop was not running for `=0`.
Removal bugs not caught in original testing because we evenly distribute liquidity, so didn't run into any payment failure - going to set liquidity to zero and re-run for a while to see if anything falls apart.

sim_network: Add unit tests + squash bugs

---

Makefile
sim-lib/src/sim_node.rs

We are currently only doing cargo check to check that our code compiles. That is good, but rustlang has a pretty good tool called clippy, that helps find non-idiomatic constructions and calls that may be error-prone.
Replaces check by clippy + fmt and fixes some existing clippy issues.

Adds clippy to gh actions and fixes clippy issues

---

README.md
sim-cli/src/main.rs
sim-lib/src/defined_activity.rs
sim-lib/src/lib.rs
sim-lib/src/random_activity.rs

Adding `start` and `count` options to the sim.json file.
`start`: Specifies when in the simulation the user wants this activity to start (for example... start sending payments at 10s)
`count`: Specifies the number of payments to send throughout the simulation (for example... send 15 payments and then stop)
Resolves #168

Issue #168: Adding optional start and count values to sim.json file

---

sim-lib/src/lib.rs

Resolves Issue #182 by removing `set.join_next()` from the `tokio::select!` statement and waiting for tasks to finish outside of the loop. Also does some error handling in the `run` function in case we encounter an error after starting data collection threads.

Issue #182 Fixes a problematic loop in produce_simulation_results

---

.github/workflows/build-and-test.yml

Pin the version of clippy that we use in CI so that new releases don't break existing CI.
Testing to see whether installing clippy at a set version will help.

workflows: pin clippy version

---

sim-lib/src/defined_activity.rs
sim-lib/src/lib.rs
sim-lib/src/serializers.rs

Values in activities can now be fixed values (e.g. 1000) or ranges (e.g. [500, 1000]).
If a range is provided, the value will be sampled uniformly at random from it.
Close #43

sim-lib: Allows amount and interval ranges in manual activity definition

---

sim-lib/src/serializers.rs

Using a more specific serialization process for the ValueOrRange type. This will allow the type to be correctly serialized and deserialized.
Close #187

Fixing the serializer for ValueOrRange

---

sim-lib/src/defined_activity.rs
sim-lib/src/lib.rs
sim-lib/src/random_activity.rs

As is, we'll run with a 0 second start delay for:
- Random activities
- Defined activities with no `start_secs` specified
This very likely isn't the intent for defined activities (people should set `start_secs=0` if they want their payments to fire immediately), and doesn't work for random activity because we just fire all payments on start.
Instead, we switch over to using our payment wait as the start delay in the absence of this field being set for defined activities and always for random activities.
Fixes #189

sim-lib: only use start delay if explicitly specified

---

README.md
sim-lib/src/lib.rs

- Follows up on #178 
- Fixes documentation nits and line length
- Updates the visibility specifier in `MutRng` and removes unnecessary `Box`ing in `MutRngType`

chore(rng): clean up documentation and RNG type

---

sim-lib/src/lib.rs

Closes Issue #196. Adds public functions to sim-lib that let a library user get the current simulation statistics.

Exposing the simulation results through public functions in sim-lib

---

.github/workflows/build-and-test.yml
Cargo.lock
Makefile
README.md
docs/ARCHITECTURE.md
docs/developer.md
sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-lib/src/lib.rs

Ran into a deadlock on shutdown when running with > 100 nodes. Cause was multiple `send` calls trying to pass events on to `receiver` channels that had already exited (because `listener` signaled that they should), example [here](https://github.com/bitcoin-dev-project/sim-ln/pull/164#discussion_r1483419179). 
This is difficult to hit with smaller networks, because most of the time everything just exits with the `listener` signal - it's only when we're in the middle of an operation in multiple tasks where we hit this. 
This PR takes the approach of just selecting on sender/listener to exit on the sender side. An alternative approach would be to use `receiver.close()` and drain the channel. This is a little more boilerplate to update all of our receiver sites, so I went with the sender …

shutdown: Select on listener on all channel sends

---

sim-lib/src/sim_node.rs

Add some validation to make sure that we get sane channels in, specifically:
- Policies that have valid max in flight / htlc size (this would be caught by our sanity checks, but this catches it early)
- No repeated channel ids, this will break other things (and can't be true irl)

sim-node: validate channel policy and enforce unique scid

---

sim-cli/src/main.rs
simln-lib/src/lib.rs

* Clean up default names in simcli
* Format imports using cargo fmt (remove whitespace)
* Fix regression for `SimulationCfg` (results moved back into cfg during rebase)

refactor/trivial: sim-cli fixups and SimulationCfg rebase regression

---

simln-lib/src/cln.rs

Resolves Issue #208 by flipping the feature bits before parsing them.

Fixing the CLN feature bit parsing

---

README.md
simln-lib/src/cln.rs
simln-lib/src/lnd.rs
simln-lib/src/serializers.rs

fix #154 
Detect if the parsed address starts with the https protocol; if not, add it without requiring a user to do it.

simln-lib/feat: Parse address detecting if starts with https

---

sim-cli/src/main.rs

Addressing https://github.com/bitcoin-dev-project/sim-ln/issues/217
Logic:
1. If sim file is present (absolute or relative, doesn't matter) - use it.
2. If it's not present as it is - fallback to the current behaviour:
a. try to join with data_dir, if it's present -great
b. if it's not present - fallback to datadir lookup
3. If it's neither present of relative path - fallback to datadir lookup.

sim-cli/bug: Interaction between simulation file path and results directory

---

Cargo.lock
sim-cli/Cargo.toml
sim-cli/src/main.rs
simln-lib/Cargo.toml
simln-lib/src/lib.rs
simln-lib/src/sim_node.rs

I ended up taking a different approach from what I mentioned here https://github.com/bitcoin-dev-project/sim-ln/pull/221#issuecomment-2707278793 to fix the memory buildup.
This adds a new dependency `tokio-util` but since it's from tokio which is already used, I though it would be ok. If not, let me know and I can try something else. 
It uses a `TaskTracker` from `tokio-util` which works very similar to a `JoinSet` but with the difference that it will free the memory from tasks when they are finished without having to call something like `join_next` for a `JoinSet`.
From their docs https://docs.rs/tokio-util/latest/tokio_util/task/task_tracker/struct.TaskTracker.html#comparison-to-joinset: 
> A [JoinSet](https://docs.rs/tokio/1.43.0/x86_64-unknown-linux-gnu/tokio/task/join_set/struct.JoinS …

fix memory buildup from JoinSet

---

.gitignore
Cargo.lock
README.md
sim-cli/src/main.rs
simln-lib/Cargo.toml
simln-lib/src/eclair.rs
simln-lib/src/lib.rs
simln-lib/src/serializers.rs

Added Eclair node support. Tracking issue: https://github.com/bitcoin-dev-project/sim-ln/issues/26
Tested on local Polar network with different use cases.

Eclair node support

---

simln-lib/src/sim_node.rs

This PR modifies the SimNode implementation to store and reuse a single ProbabilisticScorer instance instead of creating a new one for each payment. This contributes to the first part of https://github.com/bitcoin-dev-project/sim-ln/issues/216 
- Added ProbabilisticScorer as a field in SimNode struct
- Modified SimNode::new() to initialize scorer
- Updated find_payment_route to accept the stored scorer reference
- Updated `DispatchPaymentTestKit` to handle Arc'd NetworkGraph and scorer reuse

Add Scorer to SimNode

---

rust-toolchain.toml

To ensure that everyone is working on same `rustc version` and has installed `rustfmt` and `clippy`

sim-ln/enhance: Add rust-toolchain.toml

---

sim-cli/src/parsing.rs

sim-cli/refactor: do not call add_node_to_maps in validate_activities

---

Cargo.lock
docker/Dockerfile
sim-cli/Cargo.toml

As reported [here](https://github.com/bitcoin-dev-project/sim-ln/issues/246), building docker image on MacOS Sonoma 14.5 is failing. 
The solution resoling this error is to build OpenSSL from source during the Rust compilation process, rather than relying on a pre-installed OpenSSL library on the system.

sim-ln/bugfix: Set OpenSSL to be built from source 

---

simln-lib/README.md
simln-lib/src/lib.rs

1. Updated doc comments in `lib.rs` 
2. Updated `README.md`
This is what it looks like when I run `cargo doc --open` locally. 
Working on a usage example with Polar. Current gRPC issue documented [here](https://github.com/jamaljsr/polar/issues/1179).

Update simln-lib docs

---

.github/workflows/push-docker-image.yml

Tag of 2.4 failed to build docker images: https://github.com/bitcoin-dev-project/sim-ln/actions/runs/14735190441/job/41375486629
Seems like an upgrade will fix this: https://github.com/orgs/community/discussions/152695
While we're here, I've bumped a whole lot of versions to their latest (w/ help from chatgpt).

github: bump actions to v4

---

.github/workflows/push-docker-image.yml
docker/Dockerfile

Changes to later versions of rust have broken our dockerfile. This change fixes our base image to the version of rust we're currently using, where the break is not present.
We'll need to fix this in future when we bump versions, but for now we make a minimum change to be able to cut the 2.4 release.
Testing this on my personal fork: https://github.com/carlaKC/sim-ln/actions/runs/14882930754
Which will push to my dockerhub account: https://hub.docker.com/r/carlakirkcohen/simln/tags

docker: fix base image to 1.85

---

Cargo.lock
README.md
sim-cli/Cargo.toml
sim-cli/src/main.rs
sim-cli/src/parsing.rs
simln-lib/src/lib.rs
simln-lib/src/sim_node.rs
simln-lib/src/test_utils.rs

simln-lib/feature: Add ability to run with mocked ln network

---

sim-cli/src/parsing.rs
simln-lib/src/clock.rs
simln-lib/src/lib.rs
simln-lib/src/sim_node.rs
simln-lib/src/test_utils.rs

This PR adds a `Clock` trait and makes `Simulation` generic over this trait so that we have the ability to mock time, as described in #81. The default implementation of this trait just thinly wraps a system clock.
For the version where we want to speed things up, we track the instant that we started our clock and apply a multiplier to speed up time passed. For example, if we're running with a multiplier of 10:
* Track our start instant as zero
* One second of "real" time passes, which is equivalent to 10 seconds of simulated time
When dealing with durations, we can simply multiply/divide to move between simulation and real time periods.
When dealing with timestamps, we use the elapsed duration since start to figure out a sped up clock time.
This PR doesn't surface the implementation …

sim-lib: add simulated clock to speed up simulations

---

README.md
sim-cli/src/parsing.rs
simln-lib/src/cln.rs
simln-lib/src/eclair.rs
simln-lib/src/lib.rs
simln-lib/src/lnd.rs
simln-lib/src/sim_node.rs
simln-lib/src/test_utils.rs

This PR pulls up the network graph to make it simpler to run node lookups using public keys and aliases. This new node lookup approach is used to allow unspecified aliases in activity destinations by confirming if node(s) with unspecified alias exists in the graph.
1. Added Graph struct to simln-lib to enable simpler node lookups.
2. Added `get_graph` function to `LightningNode` trait and implemented it in the different LN implementations.
3. Refactored activities validation to run lookup against Graph directly.
4. Enabled mapping of duplicate aliases in alias_node_map and nodes_by_alias. 
This PR closes #227

Allow unspecified alias destinations

---

simln-lib/src/lib.rs
simln-lib/src/random_activity.rs

This PR introduces a deterministic yet unique random number generation system for the Lightning Network simulation. Each `NetworkGraphView` now maintains a base seed, while individual nodes receive their own RNG instances derived from this base seed and salted with their public keys. This ensures consistent but varied behavior across the network while preserving reproducibility.
- Added seed field to `MutRng` struct
- Implemented salted method that creates node-specific RNGs by combining the original seed with the node's public key
- Updated `random_activity_nodes` to use salted RNGs for each node

 Implement Distinct RNG Sequences 

---

simln-lib/src/sim_node.rs

doing as a prefactor for https://github.com/bitcoin-dev-project/sim-ln/pull/261 
Previously we were checking for critical errors with `is_critical` on the `ForwardingError` to trigger a simulation shutdown. Added a `CriticalError` type that includes the errors we considered critical and now returning them throughout the payment propagation in nested results to better differentiate between the 2 types of errors.

simln-lib: refactor ForwardingError to nested results

---

Cargo.lock
sim-cli/src/main.rs
sim-cli/src/parsing.rs
simln-lib/Cargo.toml
simln-lib/src/latency_interceptor.rs
simln-lib/src/lib.rs
simln-lib/src/sim_node.rs

for https://github.com/bitcoin-dev-project/sim-ln/issues/255
Mostly took changes from these 2 commits to add an `Interceptor` trait:
- https://github.com/carlaKC/sim-ln/commit/c5d7649d0969f524dc1076760128338f38853ed8 
- https://github.com/carlaKC/sim-ln/commit/228706ca3ef70d6111535ae75ef09af724dea448
Some of the things I changed from those commits:
- `intercept_htlc` now returns a `Result` to communicate the result of the intercepted htlc instead of sending it through a channel.
- spawns a task in a `JoinSet` for each interceptor's `intercept_htlc` so that if any of those holds the htlc for a long time it does not block the other interceptors. It then waits for the completion of the tasks in the joinset. If any of them returns a result to fail the htlc, it drops the `JoinSet` since there …

simln-lib: add htlc interceptor for simulated nodes

---

sim-cli/src/main.rs
sim-cli/src/parsing.rs
simln-lib/src/clock.rs

I think it'd be easier to use `create_simulation_with_network` outside of `sim-cli` if it took a `SimulationCfg` instead of the `cli`.

pass cfg to `create_simulation_with_network` 

---

simln-lib/src/cln.rs

Closes #286 
This PR adds error messages from the CLN node during startup to help with debugging. Currently, we only log a custom message and ignore app errors.

Simln-lib: log the specific error message that CLN encounters during startup

---

sim-cli/src/main.rs
sim-cli/src/parsing.rs

If using SimLN as a library, you may want to use the sped up simulation clock in other places. Pass the clock into create_simulation_with_network so that it can be created (and used) externally, and the helper function just sets up the simulation using the clock it is provided.
An alternative approach to this would be to make the Simulation::clock pub, but the downside of this is that you can hit circular dependencies
- for example, if you want to use the clock in an interceptor: you need the clock to create the interceptor, but you need to interceptor to create the simulation and thus the clock.

sim-cli/refactor: pass clock into create_simulation_with_network

---

sim-cli/src/parsing.rs

When we want to exclude nodes from random activity generation, we may still want to include them in our map of network nodes so that the caller can use any node in the network.

sim-cli: exclude nodes from simulation but not from returned map

---

simln-lib/src/lib.rs
simln-lib/src/test_utils.rs

Depends on #277.
This PR contains some follow ups for this PR, primarily style fixes and refactors.

Deterministic Payment Event Follow Ups

---

sim-cli/src/parsing.rs
simln-lib/src/lib.rs
simln-lib/src/sim_node.rs

This PR reports pathfinding outcomes to scorer in SimNode. This significantly improves the realism of pathfinding simulations by allowing the scorer to update based on actual payment success or failure.
This is an attempt to complete the work started on this [branch](https://github.com/carlaKC/sim-ln/tree/279-report-payments).
- Payment path now tracked in `SimNode.in_flight` using `InFlightPayment`.
- Added `IndexFailure` `PaymentOutcome` variant, which specifically captures the index of the channel in the payment path that caused the failure.
- Now tracking simulation time in `SimNode` using `SimulationClock` for accurate duration reporting.
- Now reporting payment success/failure to `SimNode.scorer` using the newly tracked path and failure index (if applicable).
This PR closes #279

Report Pathfinding Outcomes to Scorer in SimNode

---

README.md

In this PR, we update the eclair config to enable keysend. Initially, we are using a config that is only applicable for running Eclair in Polar. `--features.keysend=optional` works only in polar [SEE](https://github.com/jamaljsr/polar/blob/master/docker/eclair/docker-entrypoint.sh#L32-L34).
We also add additional configuration to enable CLN to send keysend payments to Eclair. Without 
```
-Declair.channel.min-final-expiry-delta-blocks
```
the payment will fail because [CLN uses 22](https://github.com/ElementsProject/lightning/blob/master/plugins/keysend.c#L237) for keysend while Eclair's minimum [default is 30](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf#L148-L149). 
```
-Declair.channel.fulfill-safety-before-timeout-blocks
```
is explicitly …

readme: fix config doc for eclair

---

sim-cli/src/parsing.rs
simln-lib/src/cln.rs
simln-lib/src/eclair.rs
simln-lib/src/lib.rs
simln-lib/src/lnd.rs
simln-lib/src/sim_node.rs
simln-lib/src/test_utils.rs

Changes:
- repurpose `list_channels` to `channel_capacities` in the `LightningNode` trait since this call was only used to determine how much the node will send per month.
- fixes bug introduced in https://github.com/bitcoin-dev-project/sim-ln/commit/39257da6cc077c34992c7962c4c3909b8200e247 where it would not return all the nodes (the ones with excluded channels). Even if we are excluding channels from nodes, we still want to return `SimNode`s so that a user could use them.

return all `SimNode`s from `ln_node_from_graph`
